#!/bin/bash
-rwxr-xr-x 1 996 992 17 0-current_working_directory 
-rwxr-xr-x 1 996 992 17 1-listit
-rwxr-xr-x 1 996 992 19 2-bring_me_home
-rwxr-xr-x 1 996 992 112 3-listfiles
-rw-r--r-- 1 996 992 18 README.md
