#!/usr/bin/env bash
#writting a script that display "to infinity..." indefinitely w "sleep 2"
#I am invincible!!! when receiving a SIGTERM signal

msg()
{
    echo "I am invincible!!!"
}
trap "msg" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2

done
