#!/usr/bin/env bash
#using commands "WHILE" repeated 9 times and using a conditional 'if' for the last line

i=1
while [ "$i" -le 10 ]
do
	echo "Best School";
if [ "$i" -eq 9 ]
then 	
	echo "Hi"
fi
(( i++ ))
done
