#!/usr/bin/env bash
i=1 
while [ "$i" -le 10 ]
	echo "Best School";
	  if [ "$i" -eq 4 ]then
	echo "Bad Luck";
	  else [ "$i" -eq 8 ] then
		  echo "Good Luck";
          elif [ "$i" > 8 ]
	  then
		 echo "Best School"
fi 
((i++))
done

