#!/usr/bin/env bash
#Working w/ conditionals 'if' 'else' 'elif'
i=1 
while [ $i -le 10 ];
do 
    if [ $i = 4 ]; 
    then
	echo "bad Luck"
	i= $ ((i+1))
elif [ $1 = 8 ];
    then
	echo "good Luck"
	i= $ ((i+1))
else
	echo "Best School"
	i= $ ((i+1))
fi 
done
