#!/usr/bin/env bash
#En el siguiente script, obtenemos la hora actual en formato de 12 horas y la hacemos eco en la consola estandarizado

while [[ $# -gt 0 ]]
  do
  key="$1"


  case $key in
  --AMPM| --ampm)
  while true;
  do
   cmd $(date +"%I")
   sleep 1s;
   clear;
done
esac
done
