#!/usr/bin/env bash
#Display the hour, 12 hours standar
#!/usr/bin/env bash

i=0
while [ "$i" -le 12 ]
do
    echo "Hour: $h"
    (( i++ ))

    x=1
    while [ "$x" -le 59 ]
    do
	echo "$x"
	(( x++ ))
    done
done
