#!/usr/bin/env bash
#En el siguiente script, obtenemos la hora actual en formato de 12 horas y la hacemos eco en la consola estandarizado
i=1
while [[ "$1" -gt 0 ]]
  do
  case $key in
  --AMPM| --ampm)
  while true;
  do
   cmd $(date +"%I")
   sleep 1s;
   clear;
done
esac
done
