#!/usr/bin/env bash
#working on gave info about the file, regular file, exists and if empty or no
#differetns forms

file="school"

if [ -e "$file" ]; then
    echo "$file file exists"

    if [ -s "$file" ]; then
	echo "$file file is not empty"
    else
	echo "$file file is empty"
    fi

    if [ -f "$file" ]; then
	echo "$file is a regular file"
    fi

else
    echo "$file file does not exist"
fi
