#!/usr/bin/env bash
#working on gave info about the file, regular file, exists and if empty or no

file="school"

if [ -e "$file" ];
then 
	echo "$file school file exists"

	if [ -s  "$file" ];
then 
	echo "$file school file is not empty"
else 	
	echo "$file school file is empty"

fi

if [ -f "$file" ]	
then 
	echo "$file school a regular file"
fi
else 
	echo "$file school does not exist"
fi
